apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: sim-operator-system
subjects:
- kind: ServiceAccount
  name: sim-operator-sim-operator-controller-manager
  namespace: sim-operator-system
roleRef:
  kind: Role
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io